=== 2830980049/HTML/target/xml/WEB-INF/classes/hr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT hr (employee+)>
<!--空格不能少 -->
<!ELEMENT employee (name,age,salary,deparment)>
<!ATTLIST employee no CDATA "">
<!ELEMENT  name (#PCDATA)>
<!ELEMENT  age (#PCDATA)>
<!ELEMENT  salary (#PCDATA)>
<!ELEMENT  deparment (dname,address)>
<!ELEMENT dname (#PCDATA)>
<!ELEMENT address (#PCDATA)>

=== 2830980049/HTML/target/xml/WEB-INF/classes/hr.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE hr SYSTEM "D:\IDEA File\HTML\src\main\resources\hr.dtd"> -->
<!-- 人力资源管理系统 -->
<!--
<hr xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hr.xsd">
-->
<hr>
    <employee no="302">
        <name>张三</name>
        <age>31</age>
        <salary>4000</salary>
        <deparment>
            <dname>会计部</dname>
            <address>大厦-B103</address>
        </deparment>
    </employee>

    <employee no="303">
        <name>德玛</name>
        <age>30</age>
        <salary>3000</salary>
        <deparment>
            <dname>工程部</dname>
            <address>大厦-B102</address>
        </deparment>
    </employee>

    <employee no="305">
        <name>苏苏</name>
        <age>20</age>
        <salary>4500</salary>
        <deparment>
            <dname>人事部</dname>
            <address>大厦-B105</address>
        </deparment>
    </employee>

</hr>
